# Generated by Django 4.1.1 on 2022-10-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('AP', 'Acrylic Paintings'), ('DA', 'Digital Art'), ('OP', 'Oil Paintings'), ('WP', 'Watercolor Paintings'), ('CR', 'Crafts')], default='AP', max_length=2)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('landscape', models.ImageField(blank=True, upload_to='media/')),
                ('portrait', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
