# Generated by Django 4.1.1 on 2022-10-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wm_landscape',
            field=models.ImageField(blank=True, upload_to='', verbose_name='watermark landscape'),
        ),
        migrations.AddField(
            model_name='product',
            name='wm_portrait',
            field=models.ImageField(blank=True, upload_to='', verbose_name='watermark portrait'),
        ),
        migrations.AlterField(
            model_name='product',
            name='landscape',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
